### ISSUE TITLE
libignition-msgs8-dev breaks libignition-msgs-dev (0) on Ubuntu

### ISSUE THREAD

**Issue by peci1** [gazebo-release/gz-msgs8-release#2]
```
$ apt show libignition-msgs8-dev
...
Breaks: libignition-msgs-dev (<= 8.2.0+ds-1)
Replaces: libignition-msgs-dev (<= 8.2.0+ds-1)
...
```

@j-rivero This breaks installation of Gazebo 9 dev package on Bionic:

```
$ sudo apt install libgazebo9-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgazebo9-dev : Depends: libignition-transport4-dev but it is not going to be installed
                  Depends: libignition-msgs-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Should it have been `Breaks: libignition-msgs8-dev (<= 8.2.0+ds-1)` in the control file?

**Comment by peci1** [comment]
@j-rivero @caguero Friendly ping. This is quite annoying on Bionic and seems to be easy to fix.

**Comment by j-rivero** [comment]
> Should it have been `Breaks: libignition-msgs8-dev (<= 8.2.0+ds-1)` in the control file?

The breaks+replaces is designed for Ubuntu Jammy where upstream packages are not versioned and that caused troubles. That hit Bionic since they share metadata. We can release new packages in Bionic with custom metadata to skip this problem. I'm going to do this.

**Comment by j-rivero** [comment]
@peci1 could please update to `8.4.0-2` and see if that fixes the problem?

**Comment by peci1** [comment]
Thank you, this fixed the issue ;)

**Comment by j-rivero** [comment]
You are welcome Martin, sorry for the delay.
